# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.12
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: 98645847+balojey@users.noreply.github.com
author_name: balo
contract_name: heba_chain
deployment_language: python
preset_name: starter
project_name: HebaChain

